"""empty message

Revision ID: 002553dd36d7
Revises: eed227297927
Create Date: 2020-04-28 21:01:48.828872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002553dd36d7'
down_revision = 'eed227297927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'epubentry', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'epubentry', type_='unique')
    # ### end Alembic commands ###
